//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bilguiden.dk.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bilguidenDBEntities : DbContext
    {
        public bilguidenDBEntities()
            : base("name=bilguidenDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Biler> Biler { get; set; }
        public virtual DbSet<Bruger> Bruger { get; set; }
        public virtual DbSet<BrugerBil> BrugerBil { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
