//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bilguiden.dk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bruger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bruger()
        {
            this.BrugerBil = new HashSet<BrugerBil>();
        }
    
        public int Bruger_ID { get; set; }
        public int BrugerBil_ID { get; set; }
        public string Fornavn { get; set; }
        public string Efternavn { get; set; }
        public string Brugernavn { get; set; }
        public string Adgangskode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BrugerBil> BrugerBil { get; set; }
    }
}
