//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bilguiden.dk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrugerBil
    {
        public int BrugerBil_ID { get; set; }
        public int Bil_ID { get; set; }
        public int Bruger_ID { get; set; }
        public Nullable<int> Kilometer { get; set; }
        public Nullable<int> Brugtpris { get; set; }
    
        public virtual Bruger Bruger { get; set; }
    }
}
